### ISSUE TITLE
Disables template linting (ember-template-lint) in Atom

### ISSUE THREAD

**Issue by amyrlam** [healthsparq/atom-ember-syntax#3]
Hi - https://github.com/healthsparq/atom-ember-syntax/issues/2 was closed, so reopening the issue here for visibility!

This packages disables eslint-ing in the Atom UI for me, any idea why?

Using this package in conjunction with these packages:

https://atom.io/packages/linter
https://atom.io/packages/linter-ui-default
https://atom.io/packages/linter-eslint
https://atom.io/packages/linter-stylelint
https://atom.io/packages/linter-ember-template

Or, do you know of other Atom packages that enable syntax highlighting for inline .hbs templates (layout: hbs in a .js file)?

//

I tried adding `source.js.extended` per https://github.com/healthsparq/atom-ember-syntax/issues/2#issuecomment-338309733, did not work, see this gif:

![31956313-e6024da6-b89f-11e7-92da-08a0eb94ecc4](https://user-images.githubusercontent.com/1372946/32196037-84309038-bd7c-11e7-9afe-2aabf649d19e.gif)

**Comment by DHedgecock** [comment]
Ahhhhhhhh, I misunderstood you, my apologies. I thought you meant ESLint no longer works, I didn't realize you were talking about handlebars linting inside of the templates.

I don't have a solution/setup for this. Seems like it should be possible. Please let us know if you dig in and find an answer!

How is the handlebars linting normally setup?

**Comment by amyrlam** [comment]
Yeah, sorry if that was confusing! Will change the title.

Regular eslint debugging e.g. add `debugger;` to a `*.js` file, totally works. 

Debugging of `*.hbs` files does not work. I'm using https://github.com/rwjblue/ember-template-lint. Yeah, I'll look into this, if you can keep it open would be cool...to see if anyone else has the same issue.

**Comment by evrowe** [comment]
For context, we are achieving inline hbs linting in our .js files via consumption of this plugin: https://www.npmjs.com/package/eslint-plugin-hbs

Adding that plugin to our eslintrc allows for inline hbs to be linted successfully

**Comment by DHedgecock** [comment]
Took a quick look, this can probably be fixed with an update to the `ember-template-lint` package. It is expecting a very specific set of grammars [see here](https://github.com/binhums/linter-ember-template/blob/master/lib/linter-ember-template.js#L11). The grammar for this package is set at `source.handlebars`.

Usually packages will try to expose a way to configure the scopes that the package will run for, because there isn't a standard (that I know of) for naming grammar scopes.

Basically you need to add `source.handlebars` to the `ember-template-lint` package like I recommended adding `source.js.extended` to the ESLint package, but there isn't an exposed configuration for it (b/c the package `ember-template-lint` is only configured to run for a few scopes of which this grammar is not one)

That linter package is also configured to run only for files (makes sense on past patterns) which would have to be updated for the new inline grammar usage.

This would be a great enhancement!

**Comment by amyrlam** [comment]
Thanks @DHedgecock ... yeah we use https://github.com/psbanka/eslint-plugin-hbs for linting inline hbs. Just want to get the syntax highlighting from your package. So many packages!

Appreciate the insight, will take a stab at it

**Comment by amyrlam** [comment]
Hey @DHedgecock, sorry for the delayed response. I ended up switching to VSCode where the highlighting is more "built-in". So feel free to close this issue if it's N/A to you...
